### ISSUE TITLE
Bundles are being registered twice

### ISSUE THREAD

**Issue by mattjohnsonpint** [johnpapa/HotTowel#3]
Both the Global.asax.cs and the HotTowelConfig.cs are registering bundles.

```
BundleConfig.RegisterBundles(BundleTable.Bundles);
```

is being called twice

**Comment by johnpapa** [comment]
The bundles must be configured in HotTowelConfig because if you install the nuget package to an existing project it has no idea where the bundles may be already. So this way it adds to them.

For the VSIX is also adds the standard global.asax, which registers the bundles too. THe double register can be removed, but it does no harm in place.
